import { ColumnConfig } from '@/widgets/database-column-setting';

export const BLUEPRINT_COLUMN_SETTING_CONFIGS: ColumnConfig[] = [
  {
    id: 'filename',
    name: 'ファイル名',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 1,
  },
  {
    id: 'orderSource',
    name: '発注元',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 2,
  },
  {
    id: 'productName',
    name: '製品名',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 3,
  },
  {
    id: 'internalNumber',
    name: '社内整番',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 4,
  },
  {
    id: 'customerNumber',
    name: '客先整番',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 5,
  },
  {
    id: 'cadName',
    name: 'CAD担当者',
    displayEnabled: false,
    filterEnabled: true,
    dataType: 'user',
    order: 6,
  },
  {
    id: 'camName',
    name: 'CAM担当者',
    displayEnabled: false,
    filterEnabled: true,
    dataType: 'user',
    order: 7,
  },
  {
    id: 'orderQuantity',
    name: '受注個数',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'number',
    order: 8,
  },
  {
    id: 'orderDate',
    name: '受注日',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'date',
    order: 9,
  },
  {
    id: 'deliveryDate',
    name: '納品日',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'date',
    order: 10,
  },
  {
    id: 'maxDimensionL',
    name: '最大長',
    displayEnabled: false,
    filterEnabled: false,
    dataType: 'number',
    order: 11,
  },
  {
    id: 'maxDimensionD',
    name: '最大幅',
    displayEnabled: false,
    filterEnabled: false,
    dataType: 'number',
    order: 12,
  },
  {
    id: 'maxDimensionH',
    name: '最大高',
    displayEnabled: false,
    filterEnabled: false,
    dataType: 'number',
    order: 13,
  },
  {
    id: 'companyField',
    name: '全社項目',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 14,
  },
];

// Blueprint固有の設定定数
export const BLUEPRINT_DATABASE_SETTING_CONFIG = {
  databaseType: 'blueprint' as const,
  pageTitle: '図面データベース設定',
  defaultColumns: BLUEPRINT_COLUMN_SETTING_CONFIGS,
} as const;