import { ColumnConfig } from '@/widgets';

// Customerに特化したカラム定義（customerColumns.tsxベース）
export const CUSTOMER_COLUMN_SETTING_CONFIGS: ColumnConfig[] = [
  {
    id: 'customerCode',
    name: '取引先コード',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 1,
  },
  {
    id: 'customerName',
    name: '取引先名',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 2,
  },
  {
    id: 'contactPerson',
    name: '取引先担当者',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'text',
    order: 3,
  },
  {
    id: 'salesRepresentative',
    name: '営業担当者',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'user',
    order: 4,
  },
  {
    id: 'phoneNumber',
    name: '電話番号',
    displayEnabled: true,
    filterEnabled: false,
    dataType: 'text',
    order: 5,
  },
  {
    id: 'faxNumber',
    name: 'FAX',
    displayEnabled: true,
    filterEnabled: false,
    dataType: 'text',
    order: 6,
  },
  {
    id: 'email',
    name: 'メールアドレス',
    displayEnabled: false,
    filterEnabled: true,
    dataType: 'text',
    order: 7,
  },
  {
    id: 'address',
    name: '住所',
    displayEnabled: false,
    filterEnabled: false,
    dataType: 'text',
    order: 8,
  },
  {
    id: 'rank',
    name: 'ランク',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'select',
    order: 9,
    options: [
      { id: 'rank-s', label: 'S', color: '#3b82f6' },
      { id: 'rank-a', label: 'A', color: '#6b7280' },
      { id: 'rank-b', label: 'B', color: '#d1d5db' },
      { id: 'rank-c', label: 'C', color: '#ef4444' },
    ],
  },
  {
    id: 'industry',
    name: '業界',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'select',
    order: 10,
    options: [
      { id: 'automotive', label: '自動車部品', color: '#10b981' },
      { id: 'industrial', label: '産業機械', color: '#3b82f6' },
      { id: 'electronics', label: '電子部品', color: '#f59e0b' },
      { id: 'food', label: '食品加工', color: '#8b5cf6' },
      { id: 'medical', label: '医療機器', color: '#ef4444' },
      { id: 'aerospace', label: '航空宇宙', color: '#06b6d4' },
      { id: 'other', label: 'その他', color: '#6b7280' },
    ],
  },
  {
    id: 'contractDate',
    name: '契約開始日',
    displayEnabled: false,
    filterEnabled: true,
    dataType: 'date',
    order: 11,
  },
  {
    id: 'lastContactDate',
    name: '最終連絡日',
    displayEnabled: false,
    filterEnabled: true,
    dataType: 'date',
    order: 12,
  },
  {
    id: 'isActive',
    name: 'アクティブ',
    displayEnabled: true,
    filterEnabled: true,
    dataType: 'boolean',
    order: 13,
  },
];

// Customer固有の設定定数
export const CUSTOMER_DATABASE_SETTING_CONFIG = {
  databaseType: 'customer' as const,
  pageTitle: '顧客データベース設定',
  defaultColumns: CUSTOMER_COLUMN_SETTING_CONFIGS,
} as const;